package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fin-health-server/graph/model"
	"fin-health-server/internal/auth"
	"fin-health-server/internal/database"
	"fin-health-server/internal/utils"
	"fmt"
	"time"

	"golang.org/x/crypto/bcrypt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	// Check if user already exists
	var existingUser database.User
	if err := r.DB.Where("email = ?", input.Email).First(&existingUser).Error; err == nil {
		return nil, fmt.Errorf("user already exists")
	}

	// Hash password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password")
	}

	// Create user
	user := database.User{
		Email:    input.Email,
		Name:     input.Name,
		Password: string(hashedPassword),
	}

	if err := r.DB.Create(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to create user")
	}

	// Seed default categories for the new user
	if err := database.SeedUserCategories(r.DB, user.ID); err != nil {
		return nil, fmt.Errorf("failed to create default categories")
	}

	// Generate token
	token, err := auth.GenerateToken(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token")
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        utils.ToSimpleGlobalID("User", user.ID),
			Email:     user.Email,
			Name:      user.Name,
			CreatedAt: user.CreatedAt.Format(time.RFC3339),
			UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	// Find user by email
	var user database.User
	if err := r.DB.Where("email = ?", input.Email).First(&user).Error; err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Check password
	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password)); err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Generate token
	token, err := auth.GenerateToken(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token")
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        utils.ToSimpleGlobalID("User", user.ID),
			Email:     user.Email,
			Name:      user.Name,
			CreatedAt: user.CreatedAt.Format(time.RFC3339),
			UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
		},
	}, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.Account, error) {
	userID := ctx.Value("user_id").(uint)

	account := database.Account{
		Name:   input.Name,
		Type:   string(input.Type),
		Icon:   input.Icon,
		UserID: userID,
	}

	if err := r.DB.Create(&account).Error; err != nil {
		return nil, fmt.Errorf("failed to create account")
	}

	// Calculate balance from sum of all transactions for this account (should be 0 for new account)
	var calculatedBalance float64
	if err := r.DB.Model(&database.Transaction{}).
		Where("account_id = ?", account.ID).
		Select("COALESCE(SUM(amount), 0)").
		Scan(&calculatedBalance).Error; err != nil {
		return nil, fmt.Errorf("failed to calculate account balance")
	}

	return &model.Account{
		ID:        utils.ToSimpleGlobalID("Account", account.ID),
		Name:      account.Name,
		Type:      model.AccountType(account.Type),
		Balance:   calculatedBalance,
		Icon:      account.Icon,
		UserID:    utils.ToSimpleGlobalID("User", account.UserID),
		CreatedAt: account.CreatedAt.Format(time.RFC3339),
		UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, id string, input model.UpdateAccountInput) (*model.Account, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid account ID")
	}
	accountID := localID

	var account database.Account
	if err := r.DB.Where("id = ? AND user_id = ?", accountID, userID).First(&account).Error; err != nil {
		return nil, fmt.Errorf("account not found")
	}

	// Update fields if provided (but not balance, which is calculated)
	if input.Name != nil {
		account.Name = *input.Name
	}
	if input.Icon != nil {
		account.Icon = *input.Icon
	}
	// Note: Balance is not updated here as it's now calculated from transactions

	if err := r.DB.Save(&account).Error; err != nil {
		return nil, fmt.Errorf("failed to update account")
	}

	// Calculate balance from sum of all transactions for this account
	var calculatedBalance float64
	if err := r.DB.Model(&database.Transaction{}).
		Where("account_id = ?", account.ID).
		Select("COALESCE(SUM(amount), 0)").
		Scan(&calculatedBalance).Error; err != nil {
		return nil, fmt.Errorf("failed to calculate account balance")
	}

	return &model.Account{
		ID:        utils.ToSimpleGlobalID("Account", account.ID),
		Name:      account.Name,
		Type:      model.AccountType(account.Type),
		Balance:   calculatedBalance,
		Icon:      account.Icon,
		UserID:    utils.ToSimpleGlobalID("User", account.UserID),
		CreatedAt: account.CreatedAt.Format(time.RFC3339),
		UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return false, fmt.Errorf("invalid account ID")
	}
	accountID := localID

	result := r.DB.Where("id = ? AND user_id = ?", accountID, userID).Delete(&database.Account{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete account")
	}

	return result.RowsAffected > 0, nil
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)
	_, accountLocalID, err := utils.FromSimpleGlobalID(input.AccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid account ID")
	}
	_, categoryLocalID, err := utils.FromSimpleGlobalID(input.CategoryID)
	if err != nil {
		return nil, fmt.Errorf("invalid category ID")
	}
	accountID := accountLocalID
	categoryID := categoryLocalID

	// Parse date
	date, err := time.Parse(time.RFC3339, input.Date)
	if err != nil {
		return nil, fmt.Errorf("invalid date format")
	}

	transaction := database.Transaction{
		Name:       input.Name,
		Amount:     input.Amount,
		Date:       date,
		Notes:      input.Notes,
		UserID:     userID,
		AccountID:  uint(accountID),
		CategoryID: uint(categoryID),
	}

	// Handle subcategory: find existing or create new one
	if input.Subcategory != "" {
		var subcategory database.Subcategory

		// First, try to find existing subcategory with this name under the given category
		err := r.DB.Where("name = ? AND category_id = ?", input.Subcategory, categoryID).First(&subcategory).Error

		if err != nil {
			// Subcategory doesn't exist, create it
			subcategory = database.Subcategory{
				Name:       input.Subcategory,
				CategoryID: uint(categoryID),
			}

			if err := r.DB.Create(&subcategory).Error; err != nil {
				return nil, fmt.Errorf("failed to create subcategory: %v", err)
			}
		}

		transaction.SubcategoryID = &subcategory.ID
	}

	if err := r.DB.Create(&transaction).Error; err != nil {
		return nil, fmt.Errorf("failed to create transaction")
	}

	var subcategoryID *string
	if transaction.SubcategoryID != nil {
		id := utils.ToSimpleGlobalID("Subcategory", *transaction.SubcategoryID)
		subcategoryID = &id
	}

	return &model.Transaction{
		ID:            utils.ToSimpleGlobalID("Transaction", transaction.ID),
		Name:          transaction.Name,
		Amount:        transaction.Amount,
		Date:          transaction.Date.Format(time.RFC3339),
		Notes:         transaction.Notes,
		HasNote:       transaction.HasNote(),
		UserID:        utils.ToSimpleGlobalID("User", transaction.UserID),
		AccountID:     utils.ToSimpleGlobalID("Account", transaction.AccountID),
		CategoryID:    utils.ToSimpleGlobalID("Category", transaction.CategoryID),
		SubcategoryID: subcategoryID,
		CreatedAt:     transaction.CreatedAt.Format(time.RFC3339),
		UpdatedAt:     transaction.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// CreateTransfer is the resolver for the createTransfer field.
func (r *mutationResolver) CreateTransfer(ctx context.Context, input model.CreateTransferInput) ([]*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)
	_, fromAccountLocalID, err := utils.FromSimpleGlobalID(input.FromAccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid from account ID")
	}
	_, toAccountLocalID, err := utils.FromSimpleGlobalID(input.ToAccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid to account ID")
	}
	fromAccountID := fromAccountLocalID
	toAccountID := toAccountLocalID

	// Verify both accounts belong to the user
	var fromAccount, toAccount database.Account
	if err := r.DB.Where("id = ? AND user_id = ?", fromAccountID, userID).First(&fromAccount).Error; err != nil {
		return nil, fmt.Errorf("from account not found")
	}
	if err := r.DB.Where("id = ? AND user_id = ?", toAccountID, userID).First(&toAccount).Error; err != nil {
		return nil, fmt.Errorf("to account not found")
	}

	// Parse date
	date, err := time.Parse(time.RFC3339, input.Date)
	if err != nil {
		return nil, fmt.Errorf("invalid date format")
	}

	// Find or create "Transfer" category
	var transferCategory database.Category
	err = r.DB.Where("name = ? AND user_id = ?", "Transfer", userID).First(&transferCategory).Error
	if err != nil {
		// Create transfer category if it doesn't exist
		transferCategory = database.Category{
			Name:   "Transfer",
			Icon:   "arrow.left.arrow.right",
			Color:  "#6c757d",
			UserID: userID,
		}
		if err := r.DB.Create(&transferCategory).Error; err != nil {
			return nil, fmt.Errorf("failed to create transfer category")
		}
	}

	// Start database transaction
	tx := r.DB.Begin()
	if tx.Error != nil {
		return nil, fmt.Errorf("failed to start transaction")
	}
	defer func() {
		if r := recover(); r != nil {
			tx.Rollback()
		}
	}()

	// Create outgoing transaction (negative amount from source account)
	outgoingTransaction := database.Transaction{
		Name:       fmt.Sprintf("Transfer to %s: %s", toAccount.Name, input.Name),
		Amount:     -input.Amount, // Negative for outgoing
		Date:       date,
		Notes:      input.Notes,
		UserID:     userID,
		AccountID:  uint(fromAccountID),
		CategoryID: transferCategory.ID,
	}

	if err := tx.Create(&outgoingTransaction).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("failed to create outgoing transaction")
	}

	// Create incoming transaction (positive amount to destination account)
	incomingTransaction := database.Transaction{
		Name:       fmt.Sprintf("Transfer from %s: %s", fromAccount.Name, input.Name),
		Amount:     input.Amount, // Positive for incoming
		Date:       date,
		Notes:      input.Notes,
		UserID:     userID,
		AccountID:  uint(toAccountID),
		CategoryID: transferCategory.ID,
	}

	if err := tx.Create(&incomingTransaction).Error; err != nil {
		tx.Rollback()
		return nil, fmt.Errorf("failed to create incoming transaction")
	}

	// Commit the transaction
	if err := tx.Commit().Error; err != nil {
		return nil, fmt.Errorf("failed to commit transfer")
	}

	// Return both transactions
	return []*model.Transaction{
		{
			ID:         utils.ToSimpleGlobalID("Transaction", outgoingTransaction.ID),
			Name:       outgoingTransaction.Name,
			Amount:     outgoingTransaction.Amount,
			Date:       outgoingTransaction.Date.Format(time.RFC3339),
			Notes:      outgoingTransaction.Notes,
			HasNote:    outgoingTransaction.HasNote(),
			UserID:     utils.ToSimpleGlobalID("User", outgoingTransaction.UserID),
			AccountID:  utils.ToSimpleGlobalID("Account", outgoingTransaction.AccountID),
			CategoryID: utils.ToSimpleGlobalID("Category", outgoingTransaction.CategoryID),
			CreatedAt:  outgoingTransaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt:  outgoingTransaction.UpdatedAt.Format(time.RFC3339),
		},
		{
			ID:         utils.ToSimpleGlobalID("Transaction", incomingTransaction.ID),
			Name:       incomingTransaction.Name,
			Amount:     incomingTransaction.Amount,
			Date:       incomingTransaction.Date.Format(time.RFC3339),
			Notes:      incomingTransaction.Notes,
			HasNote:    incomingTransaction.HasNote(),
			UserID:     utils.ToSimpleGlobalID("User", incomingTransaction.UserID),
			AccountID:  utils.ToSimpleGlobalID("Account", incomingTransaction.AccountID),
			CategoryID: utils.ToSimpleGlobalID("Category", incomingTransaction.CategoryID),
			CreatedAt:  incomingTransaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt:  incomingTransaction.UpdatedAt.Format(time.RFC3339),
		},
	}, nil
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, id string, input model.UpdateTransactionInput) (*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid transaction ID")
	}
	transactionID := localID

	var transaction database.Transaction
	if err := r.DB.Where("id = ? AND user_id = ?", transactionID, userID).First(&transaction).Error; err != nil {
		return nil, fmt.Errorf("transaction not found")
	}

	// Update fields if provided
	if input.Name != nil {
		transaction.Name = *input.Name
	}
	if input.Amount != nil {
		transaction.Amount = *input.Amount
	}
	if input.Date != nil {
		date, err := time.Parse(time.RFC3339, *input.Date)
		if err != nil {
			return nil, fmt.Errorf("invalid date format")
		}
		transaction.Date = date
	}
	if input.Notes != nil {
		transaction.Notes = input.Notes
	}
	if input.AccountID != nil {
		_, accountLocalID, err := utils.FromSimpleGlobalID(*input.AccountID)
		if err != nil {
			return nil, fmt.Errorf("invalid account ID")
		}
		transaction.AccountID = accountLocalID
	}
	if input.CategoryID != nil {
		_, categoryLocalID, err := utils.FromSimpleGlobalID(*input.CategoryID)
		if err != nil {
			return nil, fmt.Errorf("invalid category ID")
		}
		transaction.CategoryID = categoryLocalID
	}
	if input.Subcategory != nil {
		if *input.Subcategory == "" {
			// Empty string means remove subcategory
			transaction.SubcategoryID = nil
		} else {
			var subcategory database.Subcategory

			// First, try to find existing subcategory with this name under the transaction's category
			err := r.DB.Where("name = ? AND category_id = ?", *input.Subcategory, transaction.CategoryID).First(&subcategory).Error

			if err != nil {
				// Subcategory doesn't exist, create it
				subcategory = database.Subcategory{
					Name:       *input.Subcategory,
					CategoryID: transaction.CategoryID,
				}

				if err := r.DB.Create(&subcategory).Error; err != nil {
					return nil, fmt.Errorf("failed to create subcategory: %v", err)
				}
			}

			transaction.SubcategoryID = &subcategory.ID
		}
	}

	if err := r.DB.Save(&transaction).Error; err != nil {
		return nil, fmt.Errorf("failed to update transaction")
	}

	var subcategoryID *string
	if transaction.SubcategoryID != nil {
		id := utils.ToSimpleGlobalID("Subcategory", *transaction.SubcategoryID)
		subcategoryID = &id
	}

	return &model.Transaction{
		ID:            utils.ToSimpleGlobalID("Transaction", transaction.ID),
		Name:          transaction.Name,
		Amount:        transaction.Amount,
		Date:          transaction.Date.Format(time.RFC3339),
		Notes:         transaction.Notes,
		HasNote:       transaction.HasNote(),
		UserID:        utils.ToSimpleGlobalID("User", transaction.UserID),
		AccountID:     utils.ToSimpleGlobalID("Account", transaction.AccountID),
		CategoryID:    utils.ToSimpleGlobalID("Category", transaction.CategoryID),
		SubcategoryID: subcategoryID,
		CreatedAt:     transaction.CreatedAt.Format(time.RFC3339),
		UpdatedAt:     transaction.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return false, fmt.Errorf("invalid transaction ID")
	}
	transactionID := localID

	result := r.DB.Where("id = ? AND user_id = ?", transactionID, userID).Delete(&database.Transaction{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete transaction")
	}

	return result.RowsAffected > 0, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	userID := ctx.Value("user_id").(uint)

	category := database.Category{
		Name:   input.Name,
		Icon:   input.Icon,
		Color:  input.Color,
		UserID: userID,
	}

	if err := r.DB.Create(&category).Error; err != nil {
		return nil, fmt.Errorf("failed to create category")
	}

	return &model.Category{
		ID:     utils.ToSimpleGlobalID("Category", category.ID),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: utils.ToSimpleGlobalID("User", category.UserID),
	}, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.UpdateCategoryInput) (*model.Category, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid category ID")
	}
	categoryID := localID

	var category database.Category
	if err := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).First(&category).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	// Update fields if provided
	if input.Name != nil {
		category.Name = *input.Name
	}
	if input.Icon != nil {
		category.Icon = *input.Icon
	}
	if input.Color != nil {
		category.Color = *input.Color
	}

	if err := r.DB.Save(&category).Error; err != nil {
		return nil, fmt.Errorf("failed to update category")
	}

	return &model.Category{
		ID:     utils.ToSimpleGlobalID("Category", category.ID),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: utils.ToSimpleGlobalID("User", category.UserID),
	}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return false, fmt.Errorf("invalid category ID")
	}
	categoryID := localID

	result := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).Delete(&database.Category{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete category")
	}

	return result.RowsAffected > 0, nil
}

// CreateSubcategory is the resolver for the createSubcategory field.
func (r *mutationResolver) CreateSubcategory(ctx context.Context, input model.CreateSubcategoryInput) (*model.Subcategory, error) {
	userID := ctx.Value("user_id").(uint)
	_, categoryLocalID, err := utils.FromSimpleGlobalID(input.CategoryID)
	if err != nil {
		return nil, fmt.Errorf("invalid category ID")
	}
	categoryID := categoryLocalID

	// Verify that the category belongs to the user
	var category database.Category
	if err := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).First(&category).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	subcategory := database.Subcategory{
		Name:       input.Name,
		CategoryID: uint(categoryID),
	}

	if err := r.DB.Create(&subcategory).Error; err != nil {
		return nil, fmt.Errorf("failed to create subcategory")
	}

	return &model.Subcategory{
		ID:         utils.ToSimpleGlobalID("Subcategory", subcategory.ID),
		Name:       subcategory.Name,
		CategoryID: utils.ToSimpleGlobalID("Category", subcategory.CategoryID),
	}, nil
}

// UpdateSubcategory is the resolver for the updateSubcategory field.
func (r *mutationResolver) UpdateSubcategory(ctx context.Context, id string, input model.UpdateSubcategoryInput) (*model.Subcategory, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid subcategory ID")
	}
	subcategoryID := localID

	var subcategory database.Subcategory
	if err := r.DB.Joins("Category").Where("subcategories.id = ? AND Category.user_id = ?", subcategoryID, userID).First(&subcategory).Error; err != nil {
		return nil, fmt.Errorf("subcategory not found")
	}

	// Update fields if provided
	if input.Name != nil {
		subcategory.Name = *input.Name
	}
	if input.CategoryID != nil {
		_, newCategoryLocalID, err := utils.FromSimpleGlobalID(*input.CategoryID)
		if err != nil {
			return nil, fmt.Errorf("invalid category ID")
		}
		// Verify that the new category belongs to the user
		var category database.Category
		if err := r.DB.Where("id = ? AND user_id = ?", newCategoryLocalID, userID).First(&category).Error; err != nil {
			return nil, fmt.Errorf("category not found")
		}
		subcategory.CategoryID = newCategoryLocalID
	}

	if err := r.DB.Save(&subcategory).Error; err != nil {
		return nil, fmt.Errorf("failed to update subcategory")
	}

	return &model.Subcategory{
		ID:         utils.ToSimpleGlobalID("Subcategory", subcategory.ID),
		Name:       subcategory.Name,
		CategoryID: utils.ToSimpleGlobalID("Category", subcategory.CategoryID),
	}, nil
}

// DeleteSubcategory is the resolver for the deleteSubcategory field.
func (r *mutationResolver) DeleteSubcategory(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return false, fmt.Errorf("invalid subcategory ID")
	}
	subcategoryID := localID

	result := r.DB.Joins("Category").Where("subcategories.id = ? AND Category.user_id = ?", subcategoryID, userID).Delete(&database.Subcategory{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete subcategory")
	}

	return result.RowsAffected > 0, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID := ctx.Value("user_id").(uint)

	var user database.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}

	return &model.User{
		ID:        utils.ToSimpleGlobalID("User", user.ID),
		Email:     user.Email,
		Name:      user.Name,
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*model.Account, error) {
	userIDValue := ctx.Value("user_id")
	fmt.Printf("DEBUG: userID from context: %v (type: %T)\n", userIDValue, userIDValue)

	if userIDValue == nil {
		return nil, fmt.Errorf("user not authenticated")
	}

	userID := userIDValue.(uint)

	var accounts []database.Account
	if err := r.DB.Where("user_id = ?", userID).Find(&accounts).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch accounts")
	}

	var result []*model.Account
	for _, account := range accounts {
		// Calculate balance from sum of all transactions for this account
		var calculatedBalance float64
		if err := r.DB.Model(&database.Transaction{}).
			Where("account_id = ?", account.ID).
			Select("COALESCE(SUM(amount), 0)").
			Scan(&calculatedBalance).Error; err != nil {
			return nil, fmt.Errorf("failed to calculate account balance")
		}

		result = append(result, &model.Account{
			ID:        utils.ToSimpleGlobalID("Account", account.ID),
			Name:      account.Name,
			Type:      model.AccountType(account.Type),
			Balance:   calculatedBalance,
			Icon:      account.Icon,
			UserID:    utils.ToSimpleGlobalID("User", account.UserID),
			CreatedAt: account.CreatedAt.Format(time.RFC3339),
			UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*model.Account, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid account ID")
	}
	accountID := localID

	var account database.Account
	if err := r.DB.Where("id = ? AND user_id = ?", accountID, userID).First(&account).Error; err != nil {
		return nil, fmt.Errorf("account not found")
	}

	// Calculate balance from sum of all transactions for this account
	var calculatedBalance float64
	if err := r.DB.Model(&database.Transaction{}).
		Where("account_id = ?", account.ID).
		Select("COALESCE(SUM(amount), 0)").
		Scan(&calculatedBalance).Error; err != nil {
		return nil, fmt.Errorf("failed to calculate account balance")
	}

	return &model.Account{
		ID:        utils.ToSimpleGlobalID("Account", account.ID),
		Name:      account.Name,
		Type:      model.AccountType(account.Type),
		Balance:   calculatedBalance,
		Icon:      account.Icon,
		UserID:    utils.ToSimpleGlobalID("User", account.UserID),
		CreatedAt: account.CreatedAt.Format(time.RFC3339),
		UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, filter *model.TransactionFilter, limit *int32, offset *int32) ([]*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)

	query := r.DB.Where("user_id = ?", userID)

	// Apply filters
	if filter != nil {
		if filter.AccountID != nil {
			query = query.Where("account_id = ?", *filter.AccountID)
		}
		if filter.CategoryID != nil {
			query = query.Where("category_id = ?", *filter.CategoryID)
		}
		if filter.SubcategoryID != nil {
			query = query.Where("subcategory_id = ?", *filter.SubcategoryID)
		}
		if filter.DateFrom != nil {
			dateFrom, _ := time.Parse(time.RFC3339, *filter.DateFrom)
			query = query.Where("date >= ?", dateFrom)
		}
		if filter.DateTo != nil {
			dateTo, _ := time.Parse(time.RFC3339, *filter.DateTo)
			query = query.Where("date <= ?", dateTo)
		}
		if filter.AmountMin != nil {
			query = query.Where("amount >= ?", *filter.AmountMin)
		}
		if filter.AmountMax != nil {
			query = query.Where("amount <= ?", *filter.AmountMax)
		}
		if filter.Search != nil {
			query = query.Where("name ILIKE ?", "%"+*filter.Search+"%")
		}
	}

	// Apply pagination
	if offset != nil {
		query = query.Offset(int(*offset))
	}
	if limit != nil {
		query = query.Limit(int(*limit))
	}

	var transactions []database.Transaction
	if err := query.Preload("Account").Preload("Category").Preload("Subcategory").Order("date DESC").Find(&transactions).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch transactions")
	}

	var result []*model.Transaction
	for _, transaction := range transactions {
		var subcategoryID *string
		if transaction.SubcategoryID != nil {
			id := utils.ToSimpleGlobalID("Subcategory", *transaction.SubcategoryID)
			subcategoryID = &id
		}

		var account *model.Account
		if transaction.Account.ID != 0 {
			// Calculate balance from sum of all transactions for this account
			var calculatedBalance float64
			if err := r.DB.Model(&database.Transaction{}).
				Where("account_id = ?", transaction.Account.ID).
				Select("COALESCE(SUM(amount), 0)").
				Scan(&calculatedBalance).Error; err != nil {
				return nil, fmt.Errorf("failed to calculate account balance")
			}

			account = &model.Account{
				ID:        utils.ToSimpleGlobalID("Account", transaction.Account.ID),
				Name:      transaction.Account.Name,
				Type:      model.AccountType(transaction.Account.Type),
				Balance:   calculatedBalance,
				Icon:      transaction.Account.Icon,
				UserID:    utils.ToSimpleGlobalID("User", transaction.Account.UserID),
				CreatedAt: transaction.Account.CreatedAt.Format(time.RFC3339),
				UpdatedAt: transaction.Account.UpdatedAt.Format(time.RFC3339),
			}
		}

		var category *model.Category
		if transaction.Category.ID != 0 {
			category = &model.Category{
				ID:     utils.ToSimpleGlobalID("Category", transaction.Category.ID),
				Name:   transaction.Category.Name,
				Icon:   transaction.Category.Icon,
				Color:  transaction.Category.Color,
				UserID: utils.ToSimpleGlobalID("User", transaction.Category.UserID),
			}
		}

		var subcategory *model.Subcategory
		if transaction.Subcategory != nil && transaction.Subcategory.ID != 0 {
			subcategory = &model.Subcategory{
				ID:         utils.ToSimpleGlobalID("Subcategory", transaction.Subcategory.ID),
				Name:       transaction.Subcategory.Name,
				CategoryID: utils.ToSimpleGlobalID("Category", transaction.Subcategory.CategoryID),
			}
		}

		result = append(result, &model.Transaction{
			ID:            utils.ToSimpleGlobalID("Transaction", transaction.ID),
			Name:          transaction.Name,
			Amount:        transaction.Amount,
			Date:          transaction.Date.Format(time.RFC3339),
			Notes:         transaction.Notes,
			HasNote:       transaction.HasNote(),
			UserID:        utils.ToSimpleGlobalID("User", transaction.UserID),
			AccountID:     utils.ToSimpleGlobalID("Account", transaction.AccountID),
			CategoryID:    utils.ToSimpleGlobalID("Category", transaction.CategoryID),
			SubcategoryID: subcategoryID,
			Account:       account,
			Category:      category,
			Subcategory:   subcategory,
			CreatedAt:     transaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt:     transaction.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id string) (*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid transaction ID")
	}
	transactionID := localID

	var transaction database.Transaction
	if err := r.DB.Preload("Account").Preload("Category").Preload("Subcategory").Where("id = ? AND user_id = ?", transactionID, userID).First(&transaction).Error; err != nil {
		return nil, fmt.Errorf("transaction not found")
	}

	var subcategoryID *string
	if transaction.SubcategoryID != nil {
		id := utils.ToSimpleGlobalID("Subcategory", *transaction.SubcategoryID)
		subcategoryID = &id
	}

	return &model.Transaction{
		ID:            utils.ToSimpleGlobalID("Transaction", transaction.ID),
		Name:          transaction.Name,
		Amount:        transaction.Amount,
		Date:          transaction.Date.Format(time.RFC3339),
		Notes:         transaction.Notes,
		HasNote:       transaction.HasNote(),
		UserID:        utils.ToSimpleGlobalID("User", transaction.UserID),
		AccountID:     utils.ToSimpleGlobalID("Account", transaction.AccountID),
		CategoryID:    utils.ToSimpleGlobalID("Category", transaction.CategoryID),
		SubcategoryID: subcategoryID,
		CreatedAt:     transaction.CreatedAt.Format(time.RFC3339),
		UpdatedAt:     transaction.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	userID := ctx.Value("user_id").(uint)

	var categories []database.Category
	if err := r.DB.Where("user_id = ?", userID).Find(&categories).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch categories")
	}

	var result []*model.Category
	for _, category := range categories {
		result = append(result, &model.Category{
			ID:     utils.ToSimpleGlobalID("Category", category.ID),
			Name:   category.Name,
			Icon:   category.Icon,
			Color:  category.Color,
			UserID: utils.ToSimpleGlobalID("User", category.UserID),
		})
	}

	return result, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	userID := ctx.Value("user_id").(uint)
	_, localID, err := utils.FromSimpleGlobalID(id)
	if err != nil {
		return nil, fmt.Errorf("invalid category ID")
	}
	categoryID := localID

	var category database.Category
	if err := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).First(&category).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	return &model.Category{
		ID:     utils.ToSimpleGlobalID("Category", category.ID),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: utils.ToSimpleGlobalID("User", category.UserID),
	}, nil
}

// NetWorth is the resolver for the netWorth field.
func (r *queryResolver) NetWorth(ctx context.Context) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	// Get all accounts for the user
	var accounts []database.Account
	if err := r.DB.Where("user_id = ?", userID).Find(&accounts).Error; err != nil {
		return 0, fmt.Errorf("failed to fetch accounts")
	}

	var totalNetWorth float64
	for _, account := range accounts {
		// Calculate balance for each account from transactions
		var accountBalance float64
		if err := r.DB.Model(&database.Transaction{}).
			Where("account_id = ?", account.ID).
			Select("COALESCE(SUM(amount), 0)").
			Scan(&accountBalance).Error; err != nil {
			return 0, fmt.Errorf("failed to calculate account balance")
		}
		totalNetWorth += accountBalance
	}

	return totalNetWorth, nil
}

// MonthlySpending is the resolver for the monthlySpending field.
func (r *queryResolver) MonthlySpending(ctx context.Context, year int32, month int32) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	startDate := time.Date(int(year), time.Month(month), 1, 0, 0, 0, 0, time.UTC)
	endDate := startDate.AddDate(0, 1, 0).Add(-time.Second)

	var totalSpending float64
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount < 0 AND date BETWEEN ? AND ?", userID, startDate, endDate).
		Select("COALESCE(SUM(ABS(amount)), 0)").Scan(&totalSpending).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate monthly spending")
	}

	return totalSpending, nil
}

// SavingsRate is the resolver for the savingsRate field.
func (r *queryResolver) SavingsRate(ctx context.Context, year int32, month int32) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	startDate := time.Date(int(year), time.Month(month), 1, 0, 0, 0, 0, time.UTC)
	endDate := startDate.AddDate(0, 1, 0).Add(-time.Second)

	var totalIncome, totalSpending float64

	// Get total income (positive transactions)
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount > 0 AND date BETWEEN ? AND ?", userID, startDate, endDate).
		Select("COALESCE(SUM(amount), 0)").Scan(&totalIncome).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate income")
	}

	// Get total spending (negative transactions)
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount < 0 AND date BETWEEN ? AND ?", userID, startDate, endDate).
		Select("COALESCE(SUM(ABS(amount)), 0)").Scan(&totalSpending).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate spending")
	}

	if totalIncome == 0 {
		return 0, nil
	}

	savingsRate := ((totalIncome - totalSpending) / totalIncome) * 100
	return savingsRate, nil
}

// DebtToIncomeRatio is the resolver for the debtToIncomeRatio field.
func (r *queryResolver) DebtToIncomeRatio(ctx context.Context) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	// Get debt accounts (credit cards, loans)
	var debtAccounts []database.Account
	if err := r.DB.Where("user_id = ? AND type IN ('CREDIT_CARD', 'LOAN')", userID).Find(&debtAccounts).Error; err != nil {
		return 0, fmt.Errorf("failed to fetch debt accounts")
	}

	var totalDebt float64
	for _, account := range debtAccounts {
		// Calculate balance for each debt account from transactions
		var accountBalance float64
		if err := r.DB.Model(&database.Transaction{}).
			Where("account_id = ?", account.ID).
			Select("COALESCE(SUM(amount), 0)").
			Scan(&accountBalance).Error; err != nil {
			return 0, fmt.Errorf("failed to calculate account balance")
		}
		// For debt accounts, negative balances represent debt
		if accountBalance < 0 {
			totalDebt += -accountBalance // Convert to positive debt amount
		}
	}

	// Get monthly income (last 30 days)
	thirtyDaysAgo := time.Now().AddDate(0, 0, -30)
	var monthlyIncome float64
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount > 0 AND date >= ?", userID, thirtyDaysAgo).
		Select("COALESCE(SUM(amount), 0)").Scan(&monthlyIncome).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate income")
	}

	if monthlyIncome == 0 {
		return 0, nil
	}

	debtToIncomeRatio := (totalDebt / monthlyIncome) * 100
	return debtToIncomeRatio, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
