package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fin-health-server/graph/model"
	"fin-health-server/internal/auth"
	"fin-health-server/internal/database"
	"fmt"
	"strconv"
	"time"

	"golang.org/x/crypto/bcrypt"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthPayload, error) {
	// Check if user already exists
	var existingUser database.User
	if err := r.DB.Where("email = ?", input.Email).First(&existingUser).Error; err == nil {
		return nil, fmt.Errorf("user already exists")
	}

	// Hash password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password")
	}

	// Create user
	user := database.User{
		Email:    input.Email,
		Name:     input.Name,
		Password: string(hashedPassword),
	}

	if err := r.DB.Create(&user).Error; err != nil {
		return nil, fmt.Errorf("failed to create user")
	}

	// Seed default categories for the new user
	if err := database.SeedUserCategories(r.DB, user.ID); err != nil {
		return nil, fmt.Errorf("failed to create default categories")
	}

	// Generate token
	token, err := auth.GenerateToken(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token")
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        strconv.Itoa(int(user.ID)),
			Email:     user.Email,
			Name:      user.Name,
			CreatedAt: user.CreatedAt.Format(time.RFC3339),
			UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthPayload, error) {
	// Find user by email
	var user database.User
	if err := r.DB.Where("email = ?", input.Email).First(&user).Error; err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Check password
	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(input.Password)); err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	// Generate token
	token, err := auth.GenerateToken(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token")
	}

	return &model.AuthPayload{
		Token: token,
		User: &model.User{
			ID:        strconv.Itoa(int(user.ID)),
			Email:     user.Email,
			Name:      user.Name,
			CreatedAt: user.CreatedAt.Format(time.RFC3339),
			UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
		},
	}, nil
}

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.CreateAccountInput) (*model.Account, error) {
	userID := ctx.Value("user_id").(uint)

	account := database.Account{
		Name:    input.Name,
		Type:    string(input.Type),
		Balance: input.Balance,
		Icon:    input.Icon,
		UserID:  userID,
	}

	if err := r.DB.Create(&account).Error; err != nil {
		return nil, fmt.Errorf("failed to create account")
	}

	return &model.Account{
		ID:        strconv.Itoa(int(account.ID)),
		Name:      account.Name,
		Type:      model.AccountType(account.Type),
		Balance:   account.Balance,
		Icon:      account.Icon,
		UserID:    strconv.Itoa(int(account.UserID)),
		CreatedAt: account.CreatedAt.Format(time.RFC3339),
		UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, id string, input model.UpdateAccountInput) (*model.Account, error) {
	userID := ctx.Value("user_id").(uint)
	accountID, _ := strconv.Atoi(id)

	var account database.Account
	if err := r.DB.Where("id = ? AND user_id = ?", accountID, userID).First(&account).Error; err != nil {
		return nil, fmt.Errorf("account not found")
	}

	// Update fields if provided
	if input.Name != nil {
		account.Name = *input.Name
	}
	if input.Balance != nil {
		account.Balance = *input.Balance
	}
	if input.Icon != nil {
		account.Icon = *input.Icon
	}

	if err := r.DB.Save(&account).Error; err != nil {
		return nil, fmt.Errorf("failed to update account")
	}

	return &model.Account{
		ID:        strconv.Itoa(int(account.ID)),
		Name:      account.Name,
		Type:      model.AccountType(account.Type),
		Balance:   account.Balance,
		Icon:      account.Icon,
		UserID:    strconv.Itoa(int(account.UserID)),
		CreatedAt: account.CreatedAt.Format(time.RFC3339),
		UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	accountID, _ := strconv.Atoi(id)

	result := r.DB.Where("id = ? AND user_id = ?", accountID, userID).Delete(&database.Account{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete account")
	}

	return result.RowsAffected > 0, nil
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)
	accountID, _ := strconv.Atoi(input.AccountID)
	categoryID, _ := strconv.Atoi(input.CategoryID)

	// Parse date
	date, err := time.Parse(time.RFC3339, input.Date)
	if err != nil {
		return nil, fmt.Errorf("invalid date format")
	}

	transaction := database.Transaction{
		Name:       input.Name,
		Amount:     input.Amount,
		Date:       date,
		Notes:      input.Notes,
		Icon:       input.Icon,
		Color:      input.Color,
		UserID:     userID,
		AccountID:  uint(accountID),
		CategoryID: uint(categoryID),
	}

	if input.SubcategoryID != nil {
		subcategoryID, _ := strconv.Atoi(*input.SubcategoryID)
		subcategoryIDUint := uint(subcategoryID)
		transaction.SubcategoryID = &subcategoryIDUint
	}

	if err := r.DB.Create(&transaction).Error; err != nil {
		return nil, fmt.Errorf("failed to create transaction")
	}

	return &model.Transaction{
		ID:        strconv.Itoa(int(transaction.ID)),
		Name:      transaction.Name,
		Amount:    transaction.Amount,
		Date:      transaction.Date.Format(time.RFC3339),
		Notes:     transaction.Notes,
		HasNote:   transaction.HasNote(),
		Icon:      transaction.Icon,
		Color:     transaction.Color,
		UserID:    strconv.Itoa(int(transaction.UserID)),
		AccountID: strconv.Itoa(int(transaction.AccountID)),
		CategoryID: strconv.Itoa(int(transaction.CategoryID)),
		CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
		UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, id string, input model.UpdateTransactionInput) (*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)
	transactionID, _ := strconv.Atoi(id)

	var transaction database.Transaction
	if err := r.DB.Where("id = ? AND user_id = ?", transactionID, userID).First(&transaction).Error; err != nil {
		return nil, fmt.Errorf("transaction not found")
	}

	// Update fields if provided
	if input.Name != nil {
		transaction.Name = *input.Name
	}
	if input.Amount != nil {
		transaction.Amount = *input.Amount
	}
	if input.Date != nil {
		date, err := time.Parse(time.RFC3339, *input.Date)
		if err != nil {
			return nil, fmt.Errorf("invalid date format")
		}
		transaction.Date = date
	}
	if input.Notes != nil {
		transaction.Notes = input.Notes
	}
	if input.Icon != nil {
		transaction.Icon = *input.Icon
	}
	if input.Color != nil {
		transaction.Color = *input.Color
	}
	if input.AccountID != nil {
		accountID, _ := strconv.Atoi(*input.AccountID)
		transaction.AccountID = uint(accountID)
	}
	if input.CategoryID != nil {
		categoryID, _ := strconv.Atoi(*input.CategoryID)
		transaction.CategoryID = uint(categoryID)
	}
	if input.SubcategoryID != nil {
		subcategoryID, _ := strconv.Atoi(*input.SubcategoryID)
		subcategoryIDUint := uint(subcategoryID)
		transaction.SubcategoryID = &subcategoryIDUint
	}

	if err := r.DB.Save(&transaction).Error; err != nil {
		return nil, fmt.Errorf("failed to update transaction")
	}

	return &model.Transaction{
		ID:        strconv.Itoa(int(transaction.ID)),
		Name:      transaction.Name,
		Amount:    transaction.Amount,
		Date:      transaction.Date.Format(time.RFC3339),
		Notes:     transaction.Notes,
		HasNote:   transaction.HasNote(),
		Icon:      transaction.Icon,
		Color:     transaction.Color,
		UserID:    strconv.Itoa(int(transaction.UserID)),
		AccountID: strconv.Itoa(int(transaction.AccountID)),
		CategoryID: strconv.Itoa(int(transaction.CategoryID)),
		CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
		UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	transactionID, _ := strconv.Atoi(id)

	result := r.DB.Where("id = ? AND user_id = ?", transactionID, userID).Delete(&database.Transaction{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete transaction")
	}

	return result.RowsAffected > 0, nil
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.CreateCategoryInput) (*model.Category, error) {
	userID := ctx.Value("user_id").(uint)

	category := database.Category{
		Name:   input.Name,
		Icon:   input.Icon,
		Color:  input.Color,
		UserID: userID,
	}

	if err := r.DB.Create(&category).Error; err != nil {
		return nil, fmt.Errorf("failed to create category")
	}

	return &model.Category{
		ID:     strconv.Itoa(int(category.ID)),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: strconv.Itoa(int(category.UserID)),
	}, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.UpdateCategoryInput) (*model.Category, error) {
	userID := ctx.Value("user_id").(uint)
	categoryID, _ := strconv.Atoi(id)

	var category database.Category
	if err := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).First(&category).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	// Update fields if provided
	if input.Name != nil {
		category.Name = *input.Name
	}
	if input.Icon != nil {
		category.Icon = *input.Icon
	}
	if input.Color != nil {
		category.Color = *input.Color
	}

	if err := r.DB.Save(&category).Error; err != nil {
		return nil, fmt.Errorf("failed to update category")
	}

	return &model.Category{
		ID:     strconv.Itoa(int(category.ID)),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: strconv.Itoa(int(category.UserID)),
	}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	categoryID, _ := strconv.Atoi(id)

	result := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).Delete(&database.Category{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete category")
	}

	return result.RowsAffected > 0, nil
}

// CreateSubcategory is the resolver for the createSubcategory field.
func (r *mutationResolver) CreateSubcategory(ctx context.Context, input model.CreateSubcategoryInput) (*model.Subcategory, error) {
	userID := ctx.Value("user_id").(uint)
	categoryID, _ := strconv.Atoi(input.CategoryID)

	// Verify that the category belongs to the user
	var category database.Category
	if err := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).First(&category).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	subcategory := database.Subcategory{
		Name:       input.Name,
		CategoryID: uint(categoryID),
	}

	if err := r.DB.Create(&subcategory).Error; err != nil {
		return nil, fmt.Errorf("failed to create subcategory")
	}

	return &model.Subcategory{
		ID:         strconv.Itoa(int(subcategory.ID)),
		Name:       subcategory.Name,
		CategoryID: strconv.Itoa(int(subcategory.CategoryID)),
	}, nil
}

// UpdateSubcategory is the resolver for the updateSubcategory field.
func (r *mutationResolver) UpdateSubcategory(ctx context.Context, id string, input model.UpdateSubcategoryInput) (*model.Subcategory, error) {
	userID := ctx.Value("user_id").(uint)
	subcategoryID, _ := strconv.Atoi(id)

	var subcategory database.Subcategory
	if err := r.DB.Joins("Category").Where("subcategories.id = ? AND Category.user_id = ?", subcategoryID, userID).First(&subcategory).Error; err != nil {
		return nil, fmt.Errorf("subcategory not found")
	}

	// Update fields if provided
	if input.Name != nil {
		subcategory.Name = *input.Name
	}
	if input.CategoryID != nil {
		newCategoryID, _ := strconv.Atoi(*input.CategoryID)
		// Verify that the new category belongs to the user
		var category database.Category
		if err := r.DB.Where("id = ? AND user_id = ?", newCategoryID, userID).First(&category).Error; err != nil {
			return nil, fmt.Errorf("category not found")
		}
		subcategory.CategoryID = uint(newCategoryID)
	}

	if err := r.DB.Save(&subcategory).Error; err != nil {
		return nil, fmt.Errorf("failed to update subcategory")
	}

	return &model.Subcategory{
		ID:         strconv.Itoa(int(subcategory.ID)),
		Name:       subcategory.Name,
		CategoryID: strconv.Itoa(int(subcategory.CategoryID)),
	}, nil
}

// DeleteSubcategory is the resolver for the deleteSubcategory field.
func (r *mutationResolver) DeleteSubcategory(ctx context.Context, id string) (bool, error) {
	userID := ctx.Value("user_id").(uint)
	subcategoryID, _ := strconv.Atoi(id)

	result := r.DB.Joins("Category").Where("subcategories.id = ? AND Category.user_id = ?", subcategoryID, userID).Delete(&database.Subcategory{})
	if result.Error != nil {
		return false, fmt.Errorf("failed to delete subcategory")
	}

	return result.RowsAffected > 0, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID := ctx.Value("user_id").(uint)

	var user database.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}

	return &model.User{
		ID:        strconv.Itoa(int(user.ID)),
		Email:     user.Email,
		Name:      user.Name,
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*model.Account, error) {
	userID := ctx.Value("user_id").(uint)

	var accounts []database.Account
	if err := r.DB.Where("user_id = ?", userID).Find(&accounts).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch accounts")
	}

	var result []*model.Account
	for _, account := range accounts {
		result = append(result, &model.Account{
			ID:        strconv.Itoa(int(account.ID)),
			Name:      account.Name,
			Type:      model.AccountType(account.Type),
			Balance:   account.Balance,
			Icon:      account.Icon,
			UserID:    strconv.Itoa(int(account.UserID)),
			CreatedAt: account.CreatedAt.Format(time.RFC3339),
			UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, id string) (*model.Account, error) {
	userID := ctx.Value("user_id").(uint)
	accountID, _ := strconv.Atoi(id)

	var account database.Account
	if err := r.DB.Where("id = ? AND user_id = ?", accountID, userID).First(&account).Error; err != nil {
		return nil, fmt.Errorf("account not found")
	}

	return &model.Account{
		ID:        strconv.Itoa(int(account.ID)),
		Name:      account.Name,
		Type:      model.AccountType(account.Type),
		Balance:   account.Balance,
		Icon:      account.Icon,
		UserID:    strconv.Itoa(int(account.UserID)),
		CreatedAt: account.CreatedAt.Format(time.RFC3339),
		UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, filter *model.TransactionFilter, limit *int32, offset *int32) ([]*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)

	query := r.DB.Where("user_id = ?", userID)

	// Apply filters
	if filter != nil {
		if filter.AccountID != nil {
			query = query.Where("account_id = ?", *filter.AccountID)
		}
		if filter.CategoryID != nil {
			query = query.Where("category_id = ?", *filter.CategoryID)
		}
		if filter.SubcategoryID != nil {
			query = query.Where("subcategory_id = ?", *filter.SubcategoryID)
		}
		if filter.DateFrom != nil {
			dateFrom, _ := time.Parse(time.RFC3339, *filter.DateFrom)
			query = query.Where("date >= ?", dateFrom)
		}
		if filter.DateTo != nil {
			dateTo, _ := time.Parse(time.RFC3339, *filter.DateTo)
			query = query.Where("date <= ?", dateTo)
		}
		if filter.AmountMin != nil {
			query = query.Where("amount >= ?", *filter.AmountMin)
		}
		if filter.AmountMax != nil {
			query = query.Where("amount <= ?", *filter.AmountMax)
		}
		if filter.Search != nil {
			query = query.Where("name ILIKE ?", "%"+*filter.Search+"%")
		}
	}

	// Apply pagination
	if offset != nil {
		query = query.Offset(int(*offset))
	}
	if limit != nil {
		query = query.Limit(int(*limit))
	}

	var transactions []database.Transaction
	if err := query.Order("date DESC").Find(&transactions).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch transactions")
	}

	var result []*model.Transaction
	for _, transaction := range transactions {
		result = append(result, &model.Transaction{
			ID:        strconv.Itoa(int(transaction.ID)),
			Name:      transaction.Name,
			Amount:    transaction.Amount,
			Date:      transaction.Date.Format(time.RFC3339),
			Notes:     transaction.Notes,
			HasNote:   transaction.HasNote(),
			Icon:      transaction.Icon,
			Color:     transaction.Color,
			UserID:    strconv.Itoa(int(transaction.UserID)),
			AccountID: strconv.Itoa(int(transaction.AccountID)),
			CategoryID: strconv.Itoa(int(transaction.CategoryID)),
			CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id string) (*model.Transaction, error) {
	userID := ctx.Value("user_id").(uint)
	transactionID, _ := strconv.Atoi(id)

	var transaction database.Transaction
	if err := r.DB.Where("id = ? AND user_id = ?", transactionID, userID).First(&transaction).Error; err != nil {
		return nil, fmt.Errorf("transaction not found")
	}

	return &model.Transaction{
		ID:        strconv.Itoa(int(transaction.ID)),
		Name:      transaction.Name,
		Amount:    transaction.Amount,
		Date:      transaction.Date.Format(time.RFC3339),
		Notes:     transaction.Notes,
		HasNote:   transaction.HasNote(),
		Icon:      transaction.Icon,
		Color:     transaction.Color,
		UserID:    strconv.Itoa(int(transaction.UserID)),
		AccountID: strconv.Itoa(int(transaction.AccountID)),
		CategoryID: strconv.Itoa(int(transaction.CategoryID)),
		CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
		UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	userID := ctx.Value("user_id").(uint)

	var categories []database.Category
	if err := r.DB.Where("user_id = ?", userID).Find(&categories).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch categories")
	}

	var result []*model.Category
	for _, category := range categories {
		result = append(result, &model.Category{
			ID:     strconv.Itoa(int(category.ID)),
			Name:   category.Name,
			Icon:   category.Icon,
			Color:  category.Color,
			UserID: strconv.Itoa(int(category.UserID)),
		})
	}

	return result, nil
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id string) (*model.Category, error) {
	userID := ctx.Value("user_id").(uint)
	categoryID, _ := strconv.Atoi(id)

	var category database.Category
	if err := r.DB.Where("id = ? AND user_id = ?", categoryID, userID).First(&category).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	return &model.Category{
		ID:     strconv.Itoa(int(category.ID)),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: strconv.Itoa(int(category.UserID)),
	}, nil
}

// NetWorth is the resolver for the netWorth field.
func (r *queryResolver) NetWorth(ctx context.Context) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	var totalBalance float64
	if err := r.DB.Model(&database.Account{}).Where("user_id = ?", userID).Select("COALESCE(SUM(balance), 0)").Scan(&totalBalance).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate net worth")
	}

	return totalBalance, nil
}

// MonthlySpending is the resolver for the monthlySpending field.
func (r *queryResolver) MonthlySpending(ctx context.Context, year int32, month int32) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	startDate := time.Date(int(year), time.Month(month), 1, 0, 0, 0, 0, time.UTC)
	endDate := startDate.AddDate(0, 1, 0).Add(-time.Second)

	var totalSpending float64
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount < 0 AND date BETWEEN ? AND ?", userID, startDate, endDate).
		Select("COALESCE(SUM(ABS(amount)), 0)").Scan(&totalSpending).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate monthly spending")
	}

	return totalSpending, nil
}

// SavingsRate is the resolver for the savingsRate field.
func (r *queryResolver) SavingsRate(ctx context.Context, year int32, month int32) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	startDate := time.Date(int(year), time.Month(month), 1, 0, 0, 0, 0, time.UTC)
	endDate := startDate.AddDate(0, 1, 0).Add(-time.Second)

	var totalIncome, totalSpending float64

	// Get total income (positive transactions)
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount > 0 AND date BETWEEN ? AND ?", userID, startDate, endDate).
		Select("COALESCE(SUM(amount), 0)").Scan(&totalIncome).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate income")
	}

	// Get total spending (negative transactions)
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount < 0 AND date BETWEEN ? AND ?", userID, startDate, endDate).
		Select("COALESCE(SUM(ABS(amount)), 0)").Scan(&totalSpending).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate spending")
	}

	if totalIncome == 0 {
		return 0, nil
	}

	savingsRate := ((totalIncome - totalSpending) / totalIncome) * 100
	return savingsRate, nil
}

// DebtToIncomeRatio is the resolver for the debtToIncomeRatio field.
func (r *queryResolver) DebtToIncomeRatio(ctx context.Context) (float64, error) {
	userID := ctx.Value("user_id").(uint)

	// Get total debt (negative account balances - credit cards, loans)
	var totalDebt float64
	if err := r.DB.Model(&database.Account{}).
		Where("user_id = ? AND type IN ('CREDIT_CARD', 'LOAN') AND balance < 0", userID).
		Select("COALESCE(SUM(ABS(balance)), 0)").Scan(&totalDebt).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate debt")
	}

	// Get monthly income (last 30 days)
	thirtyDaysAgo := time.Now().AddDate(0, 0, -30)
	var monthlyIncome float64
	if err := r.DB.Model(&database.Transaction{}).
		Where("user_id = ? AND amount > 0 AND date >= ?", userID, thirtyDaysAgo).
		Select("COALESCE(SUM(amount), 0)").Scan(&monthlyIncome).Error; err != nil {
		return 0, fmt.Errorf("failed to calculate income")
	}

	if monthlyIncome == 0 {
		return 0, nil
	}

	debtToIncomeRatio := (totalDebt / monthlyIncome) * 100
	return debtToIncomeRatio, nil
}

// User is the resolver for the user field.
func (r *accountResolver) User(ctx context.Context, obj *model.Account) (*model.User, error) {
	userID, _ := strconv.Atoi(obj.UserID)

	var user database.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}

	return &model.User{
		ID:        strconv.Itoa(int(user.ID)),
		Email:     user.Email,
		Name:      user.Name,
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Transactions is the resolver for the transactions field.
func (r *accountResolver) Transactions(ctx context.Context, obj *model.Account) ([]*model.Transaction, error) {
	accountID, _ := strconv.Atoi(obj.ID)

	var transactions []database.Transaction
	if err := r.DB.Where("account_id = ?", accountID).Find(&transactions).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch transactions")
	}

	var result []*model.Transaction
	for _, transaction := range transactions {
		result = append(result, &model.Transaction{
			ID:        strconv.Itoa(int(transaction.ID)),
			Name:      transaction.Name,
			Amount:    transaction.Amount,
			Date:      transaction.Date.Format(time.RFC3339),
			Notes:     transaction.Notes,
			HasNote:   transaction.HasNote(),
			Icon:      transaction.Icon,
			Color:     transaction.Color,
			UserID:    strconv.Itoa(int(transaction.UserID)),
			AccountID: strconv.Itoa(int(transaction.AccountID)),
			CategoryID: strconv.Itoa(int(transaction.CategoryID)),
			CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *categoryResolver) User(ctx context.Context, obj *model.Category) (*model.User, error) {
	userID, _ := strconv.Atoi(obj.UserID)

	var user database.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}

	return &model.User{
		ID:        strconv.Itoa(int(user.ID)),
		Email:     user.Email,
		Name:      user.Name,
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Subcategories is the resolver for the subcategories field.
func (r *categoryResolver) Subcategories(ctx context.Context, obj *model.Category) ([]*model.Subcategory, error) {
	categoryID, _ := strconv.Atoi(obj.ID)

	var subcategories []database.Subcategory
	if err := r.DB.Where("category_id = ?", categoryID).Find(&subcategories).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch subcategories")
	}

	var result []*model.Subcategory
	for _, subcategory := range subcategories {
		result = append(result, &model.Subcategory{
			ID:         strconv.Itoa(int(subcategory.ID)),
			Name:       subcategory.Name,
			CategoryID: strconv.Itoa(int(subcategory.CategoryID)),
		})
	}

	return result, nil
}

// Transactions is the resolver for the transactions field.
func (r *categoryResolver) Transactions(ctx context.Context, obj *model.Category) ([]*model.Transaction, error) {
	categoryID, _ := strconv.Atoi(obj.ID)

	var transactions []database.Transaction
	if err := r.DB.Where("category_id = ?", categoryID).Find(&transactions).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch transactions")
	}

	var result []*model.Transaction
	for _, transaction := range transactions {
		result = append(result, &model.Transaction{
			ID:        strconv.Itoa(int(transaction.ID)),
			Name:      transaction.Name,
			Amount:    transaction.Amount,
			Date:      transaction.Date.Format(time.RFC3339),
			Notes:     transaction.Notes,
			HasNote:   transaction.HasNote(),
			Icon:      transaction.Icon,
			Color:     transaction.Color,
			UserID:    strconv.Itoa(int(transaction.UserID)),
			AccountID: strconv.Itoa(int(transaction.AccountID)),
			CategoryID: strconv.Itoa(int(transaction.CategoryID)),
			CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Category is the resolver for the category field.
func (r *subcategoryResolver) Category(ctx context.Context, obj *model.Subcategory) (*model.Category, error) {
	categoryID, _ := strconv.Atoi(obj.CategoryID)

	var category database.Category
	if err := r.DB.First(&category, categoryID).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	return &model.Category{
		ID:     strconv.Itoa(int(category.ID)),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: strconv.Itoa(int(category.UserID)),
	}, nil
}

// Transactions is the resolver for the transactions field.
func (r *subcategoryResolver) Transactions(ctx context.Context, obj *model.Subcategory) ([]*model.Transaction, error) {
	subcategoryID, _ := strconv.Atoi(obj.ID)

	var transactions []database.Transaction
	if err := r.DB.Where("subcategory_id = ?", subcategoryID).Find(&transactions).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch transactions")
	}

	var result []*model.Transaction
	for _, transaction := range transactions {
		result = append(result, &model.Transaction{
			ID:        strconv.Itoa(int(transaction.ID)),
			Name:      transaction.Name,
			Amount:    transaction.Amount,
			Date:      transaction.Date.Format(time.RFC3339),
			Notes:     transaction.Notes,
			HasNote:   transaction.HasNote(),
			Icon:      transaction.Icon,
			Color:     transaction.Color,
			UserID:    strconv.Itoa(int(transaction.UserID)),
			AccountID: strconv.Itoa(int(transaction.AccountID)),
			CategoryID: strconv.Itoa(int(transaction.CategoryID)),
			CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// User is the resolver for the user field.
func (r *transactionResolver) User(ctx context.Context, obj *model.Transaction) (*model.User, error) {
	userID, _ := strconv.Atoi(obj.UserID)

	var user database.User
	if err := r.DB.First(&user, userID).Error; err != nil {
		return nil, fmt.Errorf("user not found")
	}

	return &model.User{
		ID:        strconv.Itoa(int(user.ID)),
		Email:     user.Email,
		Name:      user.Name,
		CreatedAt: user.CreatedAt.Format(time.RFC3339),
		UpdatedAt: user.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Account is the resolver for the account field.
func (r *transactionResolver) Account(ctx context.Context, obj *model.Transaction) (*model.Account, error) {
	accountID, _ := strconv.Atoi(obj.AccountID)

	var account database.Account
	if err := r.DB.First(&account, accountID).Error; err != nil {
		return nil, fmt.Errorf("account not found")
	}

	return &model.Account{
		ID:        strconv.Itoa(int(account.ID)),
		Name:      account.Name,
		Type:      model.AccountType(account.Type),
		Balance:   account.Balance,
		Icon:      account.Icon,
		UserID:    strconv.Itoa(int(account.UserID)),
		CreatedAt: account.CreatedAt.Format(time.RFC3339),
		UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Category is the resolver for the category field.
func (r *transactionResolver) Category(ctx context.Context, obj *model.Transaction) (*model.Category, error) {
	categoryID, _ := strconv.Atoi(obj.CategoryID)

	var category database.Category
	if err := r.DB.First(&category, categoryID).Error; err != nil {
		return nil, fmt.Errorf("category not found")
	}

	return &model.Category{
		ID:     strconv.Itoa(int(category.ID)),
		Name:   category.Name,
		Icon:   category.Icon,
		Color:  category.Color,
		UserID: strconv.Itoa(int(category.UserID)),
	}, nil
}

// Subcategory is the resolver for the subcategory field.
func (r *transactionResolver) Subcategory(ctx context.Context, obj *model.Transaction) (*model.Subcategory, error) {
	if obj.SubcategoryID == nil {
		return nil, nil
	}

	subcategoryID, _ := strconv.Atoi(*obj.SubcategoryID)

	var subcategory database.Subcategory
	if err := r.DB.First(&subcategory, subcategoryID).Error; err != nil {
		return nil, fmt.Errorf("subcategory not found")
	}

	return &model.Subcategory{
		ID:         strconv.Itoa(int(subcategory.ID)),
		Name:       subcategory.Name,
		CategoryID: strconv.Itoa(int(subcategory.CategoryID)),
	}, nil
}

// HasNote is the resolver for the hasNote field.
func (r *transactionResolver) HasNote(ctx context.Context, obj *model.Transaction) (bool, error) {
	return obj.Notes != nil && *obj.Notes != "", nil
}

// Accounts is the resolver for the accounts field.
func (r *userResolver) Accounts(ctx context.Context, obj *model.User) ([]*model.Account, error) {
	userID, _ := strconv.Atoi(obj.ID)

	var accounts []database.Account
	if err := r.DB.Where("user_id = ?", userID).Find(&accounts).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch accounts")
	}

	var result []*model.Account
	for _, account := range accounts {
		result = append(result, &model.Account{
			ID:        strconv.Itoa(int(account.ID)),
			Name:      account.Name,
			Type:      model.AccountType(account.Type),
			Balance:   account.Balance,
			Icon:      account.Icon,
			UserID:    strconv.Itoa(int(account.UserID)),
			CreatedAt: account.CreatedAt.Format(time.RFC3339),
			UpdatedAt: account.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Transactions is the resolver for the transactions field.
func (r *userResolver) Transactions(ctx context.Context, obj *model.User) ([]*model.Transaction, error) {
	userID, _ := strconv.Atoi(obj.ID)

	var transactions []database.Transaction
	if err := r.DB.Where("user_id = ?", userID).Find(&transactions).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch transactions")
	}

	var result []*model.Transaction
	for _, transaction := range transactions {
		result = append(result, &model.Transaction{
			ID:        strconv.Itoa(int(transaction.ID)),
			Name:      transaction.Name,
			Amount:    transaction.Amount,
			Date:      transaction.Date.Format(time.RFC3339),
			Notes:     transaction.Notes,
			HasNote:   transaction.HasNote(),
			Icon:      transaction.Icon,
			Color:     transaction.Color,
			UserID:    strconv.Itoa(int(transaction.UserID)),
			AccountID: strconv.Itoa(int(transaction.AccountID)),
			CategoryID: strconv.Itoa(int(transaction.CategoryID)),
			CreatedAt: transaction.CreatedAt.Format(time.RFC3339),
			UpdatedAt: transaction.UpdatedAt.Format(time.RFC3339),
		})
	}

	return result, nil
}

// Categories is the resolver for the categories field.
func (r *userResolver) Categories(ctx context.Context, obj *model.User) ([]*model.Category, error) {
	userID, _ := strconv.Atoi(obj.ID)

	var categories []database.Category
	if err := r.DB.Where("user_id = ?", userID).Find(&categories).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch categories")
	}

	var result []*model.Category
	for _, category := range categories {
		result = append(result, &model.Category{
			ID:     strconv.Itoa(int(category.ID)),
			Name:   category.Name,
			Icon:   category.Icon,
			Color:  category.Color,
			UserID: strconv.Itoa(int(category.UserID)),
		})
	}

	return result, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }


type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type accountResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type subcategoryResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
type userResolver struct{ *Resolver }