services:
  postgres:
    image: postgres:16-alpine
    container_name: fin_health_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: finhealth
      POSTGRES_PASSWORD: finhealth_dev
      POSTGRES_DB: finhealth
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
