-- Backfill amountUsd for USD transactions that were inserted with the schema
-- default (0) instead of a correct amountUsd/exchangeRate. This affected
-- transactions generated by the recurring transaction generator before it
-- started populating amountUsd, exchangeRate, and currency explicitly.
UPDATE "Transaction"
SET "amountUsd" = "amount", "exchangeRate" = 1
WHERE "amountUsd" = 0 AND "currency" = 'USD';
