// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Account struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	Type         AccountType    `json:"type"`
	Balance      float64        `json:"balance"`
	Icon         string         `json:"icon"`
	UserID       string         `json:"userId"`
	User         *User          `json:"user"`
	Transactions []*Transaction `json:"transactions"`
	CreatedAt    string         `json:"createdAt"`
	UpdatedAt    string         `json:"updatedAt"`
}

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Category struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Icon          string         `json:"icon"`
	Color         string         `json:"color"`
	UserID        string         `json:"userId"`
	User          *User          `json:"user"`
	Subcategories []*Subcategory `json:"subcategories"`
	Transactions  []*Transaction `json:"transactions"`
}

type CreateAccountInput struct {
	Name string      `json:"name"`
	Type AccountType `json:"type"`
	Icon string      `json:"icon"`
}

type CreateCategoryInput struct {
	Name  string `json:"name"`
	Icon  string `json:"icon"`
	Color string `json:"color"`
}

type CreateSubcategoryInput struct {
	Name       string `json:"name"`
	CategoryID string `json:"categoryId"`
}

type CreateTransactionInput struct {
	Name        string  `json:"name"`
	Amount      float64 `json:"amount"`
	Date        string  `json:"date"`
	Notes       *string `json:"notes,omitempty"`
	Icon        string  `json:"icon"`
	Color       string  `json:"color"`
	AccountID   string  `json:"accountId"`
	CategoryID  string  `json:"categoryId"`
	Subcategory *string `json:"subcategory,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Name     string `json:"name"`
}

type Subcategory struct {
	ID           string         `json:"id"`
	Name         string         `json:"name"`
	CategoryID   string         `json:"categoryId"`
	Category     *Category      `json:"category"`
	Transactions []*Transaction `json:"transactions"`
}

type Transaction struct {
	ID            string       `json:"id"`
	Name          string       `json:"name"`
	Amount        float64      `json:"amount"`
	Date          string       `json:"date"`
	Notes         *string      `json:"notes,omitempty"`
	HasNote       bool         `json:"hasNote"`
	Icon          string       `json:"icon"`
	Color         string       `json:"color"`
	UserID        string       `json:"userId"`
	User          *User        `json:"user"`
	AccountID     string       `json:"accountId"`
	Account       *Account     `json:"account"`
	CategoryID    string       `json:"categoryId"`
	Category      *Category    `json:"category"`
	SubcategoryID *string      `json:"subcategoryId,omitempty"`
	Subcategory   *Subcategory `json:"subcategory,omitempty"`
	CreatedAt     string       `json:"createdAt"`
	UpdatedAt     string       `json:"updatedAt"`
}

type TransactionFilter struct {
	AccountID     *string  `json:"accountId,omitempty"`
	CategoryID    *string  `json:"categoryId,omitempty"`
	SubcategoryID *string  `json:"subcategoryId,omitempty"`
	DateFrom      *string  `json:"dateFrom,omitempty"`
	DateTo        *string  `json:"dateTo,omitempty"`
	AmountMin     *float64 `json:"amountMin,omitempty"`
	AmountMax     *float64 `json:"amountMax,omitempty"`
	Search        *string  `json:"search,omitempty"`
}

type UpdateAccountInput struct {
	Name    *string  `json:"name,omitempty"`
	Balance *float64 `json:"balance,omitempty"`
	Icon    *string  `json:"icon,omitempty"`
}

type UpdateCategoryInput struct {
	Name  *string `json:"name,omitempty"`
	Icon  *string `json:"icon,omitempty"`
	Color *string `json:"color,omitempty"`
}

type UpdateSubcategoryInput struct {
	Name       *string `json:"name,omitempty"`
	CategoryID *string `json:"categoryId,omitempty"`
}

type UpdateTransactionInput struct {
	Name        *string  `json:"name,omitempty"`
	Amount      *float64 `json:"amount,omitempty"`
	Date        *string  `json:"date,omitempty"`
	Notes       *string  `json:"notes,omitempty"`
	Icon        *string  `json:"icon,omitempty"`
	Color       *string  `json:"color,omitempty"`
	AccountID   *string  `json:"accountId,omitempty"`
	CategoryID  *string  `json:"categoryId,omitempty"`
	Subcategory *string  `json:"subcategory,omitempty"`
}

type User struct {
	ID           string         `json:"id"`
	Email        string         `json:"email"`
	Name         string         `json:"name"`
	CreatedAt    string         `json:"createdAt"`
	UpdatedAt    string         `json:"updatedAt"`
	Accounts     []*Account     `json:"accounts"`
	Transactions []*Transaction `json:"transactions"`
	Categories   []*Category    `json:"categories"`
}

type AccountType string

const (
	AccountTypeChecking   AccountType = "CHECKING"
	AccountTypeSavings    AccountType = "SAVINGS"
	AccountTypeCreditCard AccountType = "CREDIT_CARD"
	AccountTypeInvestment AccountType = "INVESTMENT"
	AccountTypeLoan       AccountType = "LOAN"
)

var AllAccountType = []AccountType{
	AccountTypeChecking,
	AccountTypeSavings,
	AccountTypeCreditCard,
	AccountTypeInvestment,
	AccountTypeLoan,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeChecking, AccountTypeSavings, AccountTypeCreditCard, AccountTypeInvestment, AccountTypeLoan:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
