import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { ArrowLeft } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function Privacy() {
  const { t } = useTranslation();

  return (
    <div className="min-h-screen bg-background px-4 py-12">
      <div className="mx-auto max-w-3xl">
        <Button asChild variant="ghost" size="sm" className="mb-8 -ml-2">
          <Link to="/login">
            <ArrowLeft className="size-4" />
            {t('legal.back')}
          </Link>
        </Button>

        <h1 className="text-3xl font-bold">{t('legal.privacyTitle')}</h1>
        <p className="mt-2 text-sm text-muted-foreground">{t('legal.privacyLastUpdated')}</p>

        <div className="mt-8 space-y-6 text-sm leading-relaxed text-muted-foreground">
          {/* Replace this block with your Privacy Policy content from Termly / Iubenda */}
          <p>
            Your privacy policy content goes here. Replace this placeholder with the full text
            generated by your legal provider (e.g., Termly or Iubenda).
          </p>
        </div>
      </div>
    </div>
  );
}
